inv/urls.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
'''
@date: 2021-01-31
@author: Shell.Xu
@copyright: 2021, Shell.Xu <shell909090@gmail.com>
@license: BSD-3-clause
'''
from django.conf.urls import url

from . import views


app_name = 'inv'

urlpatterns = [
    url(r'st/(?P<projid>[0-9]+)',
        views.proj_stat, name='proj_stat'),
    url(r'bal',
        views.balance_sheet, name='balance_sheet'),
    url(r'ios',
        views.income_outgoing_sheet, name='income_outgoing_sheet'),
    url(r'ind',
        views.income_details, name='income_details'),
    url(r'ogd',
        views.outgoing_details, name='outgoing_details'),
]

invmgr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url='/inv/bal')),
    path('admin/', admin.site.urls),
    path('inv/', include('inv.urls'))
]

inv/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
import decimal
import datetime

from scipy.optimize import fsolve

from django.db import models
from django.urls import reverse
from django.utils.html import format_html


class Currency(models.Model):

    class Meta:
        verbose_name = '币种'
        verbose_name_plural = '币种'

    name = models.CharField('货币名称', max_length=20)
    rate = models.DecimalField('汇率', max_digits=12, decimal_places=4)

    def __str__(self):
        return self.name

    def update_current_price(self):
        if self.name == 'CNY':
            return
        from . import drivers
        price = drivers.InvestingCurrency(self.name)
        if price:
            self.rate = decimal.Decimal(price)
            self.save()


class Category(models.Model):

    class Meta:
        verbose_name = '类别'
        verbose_name_plural = '类别'

    CAT_CHOICES = (
        (1, '流动资产'),
        (2, '流动负债'),
        (3, '固定资产'),
        (4, '长期负债'),
        (5, '投资'),
    )

    name = models.CharField('名称', max_length=20)
    cat = models.IntegerField('类别', choices=CAT_CHOICES)
    driver = models.CharField('数据驱动', max_length=40, blank=True, null=True)

    def __str__(self):
        return self.name

    def values_by_currency(self):
        values = {}
        for a in self.account_set.all():
            values[a.currency.name] = a.value + values.get(a.currency.name, 0)
        for p in self.invproj_set.filter(isopen=True).all():
            values[p.acct.currency.name] = p.value + values.get(p.acct.currency.name, 0)
        return values
        

class Bank(models.Model):

    class Meta:
        verbose_name = '银行'
        verbose_name_plural = '银行'

    name = models.CharField('名称', max_length=20)

    def __str__(self):
        return self.name


class Account(models.Model):

    class Meta:
        verbose_name = '账户'
        verbose_name_plural = '账户'

    bank = models.ForeignKey(Bank, verbose_name='银行', on_delete=models.PROTECT)
    name = models.CharField('名称', max_length=20)
    currency = models.ForeignKey(Currency, verbose_name='币种',
                                 on_delete=models.PROTECT)
    cat = models.ForeignKey(Category, verbose_name='类别', on_delete=models.PROTECT)
    value = models.DecimalField('余额', max_digits=16, decimal_places=2)

    def __str__(self):
        return f'{self.bank.name}-{self.name}'


class AccountCategory(models.Model):

    class Meta:
        verbose_name = '账户收支类别'
        verbose_name_plural = '账户收支类别'

    CAT_CHOICES = (
        (1, '收入'),
        (2, '支出'),
    )

    name = models.CharField('名称', max_length=20)
    cat = models.IntegerField('收支', choices=CAT_CHOICES)

    def __str__(self):
        return self.name


class AccountRec(models.Model):

    class Meta:
        verbose_name = '账户收支'
        verbose_name_plural = '账户收支'

    acct = models.ForeignKey(Account, verbose_name='账户',
                             on_delete=models.PROTECT, blank=True, null=True)
    date = models.DateField('日期')
    cat = models.ForeignKey(AccountCategory, verbose_name='账户收支类别',
                            on_delete=models.PROTECT)
    value = models.DecimalField('金额', max_digits=16, decimal_places=2)
    comment = models.CharField('注释', max_length=200, blank=True, null=True)

    def __str__(self):
        return f'{self.acct}({self.date})'


class Risk(models.Model):

    class Meta:
        verbose_name = '风险级别'
        verbose_name_plural = '风险级别'

    name = models.CharField('名称', max_length=20)

    def __str__(self):
        return self.name


class InvProj(models.Model):

    class Meta:
        verbose_name = '投资项目'
        verbose_name_plural = '投资项目'

    name = models.CharField('名称', max_length=100)
    code = models.CharField('代码', max_length=50, blank=True, null=True)
    url =  models.URLField('链接', max_length=200, blank=True, null=True)
    acct = models.ForeignKey(Account, verbose_name='账户',
                             on_delete=models.PROTECT)
    cat = models.ForeignKey(Category, verbose_name='类别',
                            on_delete=models.PROTECT)
    risk = models.ForeignKey(Risk, verbose_name='风险级别',
                             on_delete=models.PROTECT)
    isopen = models.BooleanField('是否存续')
    start = models.DateField('开始日期', blank=True, null=True)
    end = models.DateField('结束日期', blank=True, null=True)
    quote_id = models.CharField('查询代号', max_length=500, blank=True, null=True)
    current_price = models.DecimalField('现价', max_digits=16, decimal_places=4,
                                        blank=True, null=True)
    buy_amount = models.DecimalField(max_digits=16, decimal_places=4, null=True)
    sell_amount = models.DecimalField(max_digits=16, decimal_places=4, null=True)
    amount = models.DecimalField(max_digits=16, decimal_places=4, null=True)
    buy_value = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    sell_value = models.DecimalField(max_digits=16, decimal_places=2, null=True)
    value = models.DecimalField('现存价值', max_digits=16, decimal_places=2,
                                null=True)
    dividends = models.DecimalField('分红', max_digits=16, decimal_places=2,
                                    null=True)
    irr = models.DecimalField('年化率', max_digits=16, decimal_places=4, null=True)
    local_irr = models.DecimalField('本币年化率', max_digits=16, decimal_places=4, null=True)
    comment = models.CharField('注释', max_length=200, blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    def currency(self):
        return self.acct.currency
    currency.short_description = '币种'

    def bank(self):
        return format_html(
            '<a href="/admin/inv/account/?bank__id__exact={bank_id}">{bank}</a>',
            bank_id=self.acct.bank.id, bank=self.acct.bank)
    bank.short_description = '银行'

    def net_value(self):
        value = -self.value
        if self.isopen and self.current_price:
            value += self.amount*self.current_price
        return format_html(
            '<a href="{link}">{value}</a>',
            link=reverse('inv:proj_stat', kwargs={'projid': self.id}),
            value='{0:0.2f}'.format(value))
    net_value.short_description = '净值'

    def buy_price(self):
        if self.buy_amount:
            return self.buy_value/self.buy_amount
    buy_price.short_description = '买入均价'

    def sell_price(self):
        if self.sell_amount:
            return self.sell_value/self.sell_amount
    sell_price.short_description = '卖出均价'

    def avg_price(self):
        if self.amount:
            return '{0:0.4f}'.format(self.value/self.amount)
    avg_price.short_description = '成本均价'

    def buy_sell_rate(self):
        income = self.sell_value+self.dividends+self.amount*self.current_price
        return 100*income/self.buy_value - 100

    def net_value_rate(self):
        if self.isopen and self.current_price and self.value:
            return 100*(self.amount*self.current_price)/self.value - 100

    def update_from_rec(self):
        self.buy_amount, self.sell_amount = 0, 0
        self.buy_value, self.sell_value = 0, 0
        self.dividends = 0
        for r in self.invrec_set.all():
            if r.cat == 1:
                self.buy_amount += r.amount
                self.buy_value += r.value
            elif r.cat == 2:
                self.sell_amount += r.amount
                self.sell_value += r.value
            elif r.cat == 3:
                self.dividends += r.value
        self.amount = self.buy_amount - self.sell_amount
        self.value = self.buy_value - self.sell_value - self.dividends

        if self.invrec_set.count():
            self.start = min((r.date for r in self.invrec_set.all()))
            if not self.isopen:
                self.end = max((r.date for r in self.invrec_set.all()))
            self.irr = self.calc_irr(False)
            self.local_irr = self.calc_irr(True)

        self.save()

    def duration(self):
        if not self.start:
            return 0
        return ((self.end or datetime.date.today())-self.start).days
    duration.short_description = '存续天数'

    def calc_iotab(self, td, local):
        for r in self.invrec_set.all():
            value = float(r.value if r.cat == 1 else -r.value)
            if local and r.rate:
                value *= float(r.rate)
            yield (td - r.date).days, value
        if self.isopen and self.current_price:
            value = float(self.amount*self.current_price)
            if local:
                value *= float(self.acct.currency.rate)
            yield 0, -value

    def calc_irr(self, local):
        if self.isopen and self.current_price:
            td = datetime.date.today()
        else:
            td = max((r.date for r in self.invrec_set.all()))

        iotab = list(self.calc_iotab(td, local))
        def f(r):
            return sum((value*r**dur for dur, value in iotab))

        r = fsolve(f, 1.01)[0]
        return 365*100*(r-1)

    def update_current_price(self):
        if not self.quote_id or not self.cat.driver:
            return
        from . import drivers
        try:
            func = getattr(drivers, self.cat.driver)
        except AttributeError:
            return
        price = func(self.quote_id)
        if price:
            self.current_price = decimal.Decimal(price)
            self.update_from_rec()
            self.save()


class InvRec(models.Model):

    class Meta:
        verbose_name = '投资记录'
        verbose_name_plural = '投资记录'

    CAT_CHOICES = (
        (1, '买'),
        (2, '卖'),
        (3, '分红'),
    )

    proj = models.ForeignKey(InvProj, verbose_name='投资项目',
                             on_delete=models.PROTECT)
    date = models.DateField('日期')
    cat = models.IntegerField('类别', choices=CAT_CHOICES)
    amount = models.DecimalField('数额', max_digits=16, decimal_places=4)

inv/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
import decimal
import datetime

import pandas as pd
from scipy.optimize import fsolve

from django.http import HttpResponse
from django.shortcuts import render

from .models import Currency, Category, Bank, Account, AccountCategory, AccountRec, Risk, InvProj, InvRec
from . import tables


def proj_stat(request, projid):
    proj = InvProj.objects.get(id=int(projid))
    tab = tables.InvRecTable(proj.invrec_set.all(), request=request)
    env = {
        'proj': proj,
        'table': tab,
    }
    return render(request, 'inv/proj_stat.html', env)


def add_vectory(a, b):
    return [i+j for i, j in zip(a, b)]


def sub_vectory(a, b):
    return [i-j for i, j in zip(a, b)]


def div_vectory(a, b):
    return [i/j for i, j in zip(a, b) if j != 0]


def balance_sheet(request):
    curs = Currency.objects.all()
    sheet = {}
    for cat in Category.objects.all():
        values = cat.values_by_currency()
        l = []
        total = 0
        for cur in curs:
            l.append(values.get(cur.name, decimal.Decimal()))
            total += values.get(cur.name, decimal.Decimal()) * cur.rate
        l.append(total)
        sheet.setdefault(cat.cat, [])
        sheet[cat.cat].append((cat, l))

    assets = [decimal.Decimal(),]*(len(curs)+1)
    liabilities = [decimal.Decimal(),]*(len(curs)+1)
    for i in range(1, 6):
        sums = [decimal.Decimal(),]*(len(curs)+1)
        for name, values in sheet[i]:
            sums = add_vectory(sums, values)
        if i == 1:
            current_asset = sums[:]
        if i == 2:
            current_liabilities = sums[:]
        if i in {1, 3, 5}:
            assets = add_vectory(assets, sums)
        else:
            liabilities = add_vectory(liabilities, sums)
        sheet[i].append(({'name': '小记'}, sums))

    liquidity_list = div_vectory(map(float, current_asset),
                                 map(float, current_liabilities))
    if liquidity_list:
        liquidity_ratio = min(liquidity_list)
    else:
        liquidity_ratio = -1
    debt_asset_ratio = max(div_vectory(map(float, liabilities),
                                       map(float, assets)))

    env = {
        'sheet': sheet,
        'curs': curs,
        'assets': assets,
        'liabilities': liabilities,
        'equity': list(sub_vectory(assets, liabilities)),
        'liquidity_ratio': liquidity_ratio,
        'debt_asset_ratio': 100*debt_asset_ratio,
    }
    return render(request, 'inv/balance_sheet.html', env)


def income_outgoing_sheet(request):
    lastyear = datetime.date.today()-datetime.timedelta(days=365)
    td = datetime.date.today()

    income = []
    for cat in AccountCategory.objects.filter(cat=1).all():
        num = sum((rec.value for rec in cat.accountrec_set.filter(date__gte=lastyear).all()))
        if num:
            income.append((cat.name, num))
    s_income = sum((n for c, n in income))
    income.append(('小计', s_income))

    outgoing = []
    for cat in AccountCategory.objects.filter(cat=2).all():
        num = sum((rec.value for rec in cat.accountrec_set.filter(date__gte=lastyear).all()))
        if num:
            outgoing.append((cat.name, num))
    s_outgoing = sum((n for c, n in outgoing))
    outgoing.append(('小计', s_outgoing))

    investments = []
    iotab = []
    for cat in Category.objects.filter(cat=5).all():
        num = 0
        for proj in cat.invproj_set.filter(isopen=False, end__gte=lastyear).all():
            num -= (proj.value*proj.acct.currency.rate).quantize(decimal.Decimal('1.00'))
            iotab.extend(proj.calc_iotab(td, True))
        if num:
            investments.append((cat.name, num))
    s_investments = sum((n for c, n in investments))
    investments.append(('小计', s_investments))

    def f(r):
        return sum((value*r**dur for dur, value in iotab))
    r = fsolve(f, 1.01)[0]

    env = {
        'income': income,
        'outgoing': outgoing,
        'investments': investments,
        'total_income': s_income+s_investments,
        'total_outgoing': s_outgoing,
        'net_income': s_income+s_investments-s_outgoing,
        'saving_rate': 100*(s_income+s_investments-s_outgoing)/(s_income+s_investments),
        'invest_income_rate': 100*s_investments/(s_income+s_investments),
        'invest_outgoing_rate': 100*s_investments/s_outgoing,
        'invest_rate': 365*100*(r-1),
    }
    return render(request, 'inv/ios.html', env)


def income_details(request):
    df = pd.DataFrame()

    for cat in AccountCategory.objects.filter(cat=1).all():
        s = pd.Series(name=cat.name)
        for rec in cat.accountrec_set.all():
            dt = rec.date.replace(day=1)
            if dt not in s:
                s[dt] = rec.value
            else:
                s[dt] += rec.value
        if s.count():
            df = df.join(s, how='outer')

    for cat in Category.objects.filter(cat=5).all():
        s = pd.Series(name=cat.name)
        for proj in cat.invproj_set.filter(isopen=False).all():
            dt = proj.end.replace(day=1)
            value = (proj.value*proj.acct.currency.rate).quantize(decimal.Decimal('1.00'))
            if dt not in s:
                s[dt] = -value
            else:
                s[dt] += -value
        if s.count():
            df = df.join(s, how='outer')

    df = df.sort_index()
    df['总计'] = df.sum(axis=1)
    env = {
        'title': '收入细节表',
        'code': df.to_html(border=0, classes='table table-striped table-responsive'),
    }
    return render(request, 'inv/raw.html', env)


def outgoing_details(request):
    df = pd.DataFrame()

    for cat in AccountCategory.objects.filter(cat=2).all():
        s = pd.Series(name=cat.name)
        for rec in cat.accountrec_set.all():
            dt = rec.date.replace(day=1)
            if dt not in s:
                s[dt] = rec.value
            else:
                s[dt] += rec.value
        if s.count():
            df = df.join(s, how='outer')
    
    df = df.sort_index()
    df['总计'] = df.sum(axis=1)
    env = {
        'title': '支出细节表',
        'code': df.to_html(border=0, classes='table table-striped table-responsive'),
    }
    return render(request, 'inv/raw.html', env)

inv/templates/inv/balance_sheet.html
{% extends 'inv/base.html' %}
{% load bootstrap3 %}

{% block title %}资产负债表{% endblock %}

{% block header %}
<style>
  .money {
      width: 16%;
      text-align: right;
  }
</style>
{% endblock %}

{% block body %}

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <table class="table table-striped table-responsive">
	<tbody>
	  <tr>
	    <td>资产</td>
	    <td></td>
	    {% for cur in curs %}
	    <td class="money">{{cur.name}}</td>
	    {% endfor %}
	    <td class="money">CNY计价</td>
	  </tr>
	  <tr>
	    <td>流动资产</td>
	    <td></td>
	    {% for cur in curs %}
	    <td></td>
	    {% endfor %}
	    <td></td>
	  </tr>
	  {% for cat in sheet.1 %}
	  <tr>
	    <td></td>
	    <td width="16%">
	      {% if cat.0.id %}
	      <a href="/admin/inv/account/?cat__id__exact={{cat.0.id}}">{{cat.0.name}}</a>
	      {% else %}
	      {{cat.0.name}}
	      {% endif %}
	    </td>
	    {% for f in cat.1 %}
	    <td class="money">{{f|floatformat:2}}</td>
	    {% endfor %}
	  </tr>
	  {% endfor %}
	</tbody>
      </table>
    </div>

    <div class="col-sm-6">
      <table class="table table-striped table-responsive">
	<tbody>
	  <tr>
	    <td>负债</td>
	    <td></td>
	    {% for cur in curs %}
	    <td class="money">{{cur.name}}</td>
	    {% endfor %}
	    <td class="money">CNY计价</td>
	  </tr>
	  <tr>
	    <td>流动负债</td>
	    <td></td>
	    {% for cur in curs %}
	    <td></td>
	    {% endfor %}
	    <td></td>
	  </tr>
	  {% for cat in sheet.2 %}
	  <tr>
	    <td></td>
	    <td width="16%">
	      {% if cat.0.id %}
	      <a href="/admin/inv/account/?cat__id__exact={{cat.0.id}}">{{cat.0.name}}</a>
	      {% else %}
	      {{cat.0.name}}
	      {% endif %}
	    </td>
	    {% for f in cat.1 %}
	    <td class="money">{{f|floatformat:2}}</td>
	    {% endfor %}
	  </tr>
	  {% endfor %}
	</tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <table class="table table-striped table-responsive">
	<tbody>
	  <tr>
	    <td>固定资产</td>
	    <td></td>
	    {% for cur in curs %}
	    <td width="16%"></td>
	    {% endfor %}
	    <td width="16%"></td>
	  </tr>
	  {% for cat in sheet.3 %}
	  <tr>
	    <td></td>
	    <td width="16%">
	      {% if cat.0.id %}
	      <a href="/admin/inv/account/?cat__id__exact={{cat.0.id}}">{{cat.0.name}}</a>
	      {% else %}
	      {{cat.0.name}}
	      {% endif %}
	    </td>
	    {% for f in cat.1 %}
	    <td class="money">{{f|floatformat:2}}</td>
	    {% endfor %}
	  </tr>
	  {% endfor %}
	</tbody>
      </table>
    </div>

    <div class="col-sm-6">
      <table class="table table-striped table-responsive">
	<tbody>
	  <tr>
	    <td>长期负债</td>
	    <td></td>
	    {% for cur in curs %}
	    <td width="16%"></td>
	    {% endfor %}
	    <td width="16%"></td>
	  </tr>
	  {% for cat in sheet.4 %}
	  <tr>
	    <td></td>
	    <td width="16%">
	      {% if cat.0.id %}
	      <a href="/admin/inv/account/?cat__id__exact={{cat.0.id}}">{{cat.0.name}}</a>
	      {% else %}
	      {{cat.0.name}}
	      {% endif %}
	    </td>
	    {% for f in cat.1 %}
	    <td class="money">{{f|floatformat:2}}</td>
	    {% endfor %}
	  </tr>
	  {% endfor %}
	</tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <table class="table table-striped table-responsive">
	<tbody>
	  <tr>
	    <td>投资</td>
	    <td></td>
	    {% for cur in curs %}
	    <td width="16%"></td>
	    {% endfor %}
	    <td width="16%"></td>
	  </tr>
	  {% for cat in sheet.5 %}
	  <tr>
	    <td></td>
	    <td width="16%">
	      {% if cat.0.id %}
	      <a href="/admin/inv/invproj/?cat__id__exact={{cat.0.id}}&isopen__exact=1">{{cat.0.name}}</a>
	      {% else %}
	      {{cat.0.name}}
	      {% endif %}
	    </td>
	    {% for f in cat.1 %}
	    <td class="money">{{f|floatformat:2}}</td>
	    {% endfor %}
	  </tr>
	  {% endfor %}
	</tbody>
      </table>
    </div>

    <div class="col-sm-6">
      <table class="table table-striped table-responsive">
	<tbody>
	  <tr>
	    <td>流动性比例</td>
	    <td class="money">{{liquidity_ratio|floatformat:-2}}</td>
	  </tr>
	  <tr>
	    <td>资产负债率</td>
	    <td class="money">{{debt_asset_ratio|floatformat:-2}}%</td>
	  </tr>
	</tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <table class="table table-striped table-responsive">
	<tbody>
	  <tr>
	    <td>总计</td>
	    <td width="16%"></td>
	    {% for f in assets %}
	    <td class="money">{{f|floatformat:2}}</td>
	    {% endfor %}
	  </tr>
	</tbody>
      </table>
    </div>

    <div class="col-sm-6">
      <table class="table table-striped table-responsive">
	<tbody>
	  <tr>
	    <td>总计</td>
	    <td width="16%"></td>
	    {% for f in liabilities %}
	    <td class="money">{{f|floatformat:2}}</td>
	    {% endfor %}
	  </tr>
	  <tr>
	    <td>净值</td>
	    <td></td>
	    {% for f in equity %}
	    <td class="money">{{f|floatformat:2}}</td>
	    {% endfor %}
	  </tr>
	</tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

inv/templates/inv/base.html
{% load bootstrap3 %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <title>{%block title%}{%endblock%}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="author" content="shell">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
      body {
          font-family: Consolas,Monaco,Lucida Console,Liberation Mono,DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New, monospace;
      }
    </style>
    {% block header %}
    {% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
	<div class="navbar-header">
	  <a class="navbar-brand" href="#">投资管理</a>
	</div>
	{% block nav_left %}
	{% endblock %}
	<ul class="nav navbar-nav navbar-left">
	  <li class="dropdown">
	    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	      功能链接
	      <span class="caret"></span>
	    </a>
	    <ul class="dropdown-menu">
	      <li><a href="/admin/">管理</a></li>
	      <li><a href="{% url 'inv:balance_sheet' %}">资产负债表</a></li>
	      <li><a href="{% url 'inv:income_outgoing_sheet' %}">收入支出表</a></li>
	      <li><a href="{% url 'inv:income_details' %}">收入细节</a></li>
	      <li><a href="{% url 'inv:outgoing_details' %}">支出细节</a></li>
	    </ul>
	  </li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	  {% block nav_right %}
	  {% endblock %}
	</ul>
      </div>
    </nav>

    {% bootstrap_messages %}

    {%block body%}
    {%endblock%}
    
    {% block script %}
    {% endblock %}
  </body>
</html>

inv/templates/inv/raw.html
{% extends 'inv/base.html' %}
{% load bootstrap3 %}

{% block title %}{{title}}{% endblock %}

{% block body %}
<div class="container-fluid">
  {{code|safe}}
</div>
{% endblock %}